name: Java CI con Gradle

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Descarga el código de tu repositorio
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Configura Java 21 (Necesario para Paper 1.21.4+)
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    # 3. Da permisos al ejecutable de Gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # 4. Compila el proyecto y crea el JAR
    - name: Build with Gradle
      run: ./gradlew build

    # 5. Guarda el archivo .jar para que puedas descargarlo
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: VillageDefense-Jar
        path: build/libs/*.jar
        if-no-files-found: error
